# Generated by Django 5.2.6 on 2025-09-16 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review_is_reported_reviewreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reporter_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of anonymous reporter', null=True),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
