# Generated by Django 5.2.6 on 2025-09-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_reviewreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='Mark as True when review is reported for inappropriate content'),
        ),
        migrations.DeleteModel(
            name='ReviewReport',
        ),
    ]
