# Generated by Django 5.2.7 on 2025-10-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_review_is_reported_delete_reviewreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('northeast', 'Northeast'), ('southeast', 'Southeast'), ('midwest', 'Midwest'), ('west', 'West')], default='northeast', max_length=20),
        ),
    ]
