# Generated by Django 5.2.6 on 2025-10-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_region'),
        ('store', '0006_rating'),
    ]

    operations = [
    ]
